import { Product } from '../types/database';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-classic-smash',
    name: 'Classic Smash Burger',
    price: 28.0,
    patty_count: 1,
    category: 'burger',
    description: 'Pão brioche, 1x blend smash 100g, queijo cheddar, picles e molho da casa',
  },
  {
    id: 'prod-double-cheddar',
    name: 'Double Smash Bacon',
    price: 36.0,
    patty_count: 2,
    category: 'burger',
    description: 'Pão brioche, 2x blend smash 100g, duplo cheddar, bacon crocante e maionese defumada',
  },
  {
    id: 'prod-monster-triple',
    name: 'Monster Triple Bacon',
    price: 44.0,
    patty_count: 3,
    category: 'burger',
    description: 'Pão brioche, 3x blend smash 100g, triplo cheddar, cebola caramelizada e barbecue',
  },
  {
    id: 'prod-smash-salad',
    name: 'Smash Salad Fresco',
    price: 30.0,
    patty_count: 1,
    category: 'burger',
    description: 'Pão brioche, 1x blend smash 100g, queijo prato, alface americana, tomate e maionese verde',
  },
  {
    id: 'prod-batata-rustica',
    name: 'Batata Rústica Alecrim',
    price: 18.0,
    patty_count: 0,
    category: 'side',
    description: 'Batatas rústicas fritas crocantes com sal de ervas e alho tostado',
  },
  {
    id: 'prod-onion-rings',
    name: 'Onion Rings Crocantes',
    price: 20.0,
    patty_count: 0,
    category: 'side',
    description: 'Anéis de cebola selecionados empanados na farinha panko',
  },
  {
    id: 'prod-coca-cola',
    name: 'Coca-Cola Lata 350ml',
    price: 7.0,
    patty_count: 0,
    category: 'drink',
    description: 'Refrigerante em lata bem gelado',
  },
  {
    id: 'prod-guarana',
    name: 'Guaraná Antarctica 350ml',
    price: 7.0,
    patty_count: 0,
    category: 'drink',
    description: 'Refrigerante em lata bem gelado',
  },
  {
    id: 'prod-agua',
    name: 'Água Mineral 500ml',
    price: 5.0,
    patty_count: 0,
    category: 'drink',
    description: 'Água mineral natural sem gás',
  },
  {
    id: 'prod-brownie',
    name: 'Brownie de Chocolate',
    price: 16.0,
    patty_count: 0,
    category: 'dessert',
    description: 'Brownie artesanal com calda de chocolate meio amargo',
  },
];
